### PR TITLE
Include active_trophy_id in findPostsByTopicId query

### PR DESCRIPTION
**Pull request by TheMaster99**
Fix Benevolent Cyberpunk fancy userbit and other trophy titles on posts by adding `active_trophy_id` to the list of columns compiled from the `users` table into the JSON object that is created in `server/db/index.js.findPostsByTopicId`

### CODE REVIEW

**Comment by TheMaster99** [comment]
Closes #170

**Comment by danneu** [comment]
Nice one, thanks. I need to do a deploy this xmas.

**Comment by TheMaster99** [comment]
Is there any particular reason this has yet to be pulled, @danneu? I'd be willing to work on more useful things than fixing trophy flairs if they were going to get used, but I'm not confident that would happen at this point since even fixing a single line has taken >5 months to be accepted. I totally understand that you're busy, and life always should take priority, but I can't help to even begin reducing the burden if I have no pipeline for getting code deployed!

**Comment by danneu** [comment]
Fixes #172

**Pull request merged**
